// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int runs = Integer.parseInt(args[0]);
		double highCounter = 0;
		double lowCounter = 0;

		for (int i = 0; i < runs; i++) {
			if (Math.random() > 0.5)
				highCounter++;
			else
				lowCounter++;
		}

		System.out.println("> 0.5:  " + (int) highCounter + " times");
		System.out.println("<= 0.5: " + (int) lowCounter + " times");
		if (lowCounter != 0)
			System.out.println("Ratio:  " + lowCounter / highCounter);
	}
}
